package:
  name: tigre
  version: 2.1

build:
  skip: True # [py==38 and np==115]
  preserve_egg_dir: False
  number: 0

  missing_dso_whitelist:
    - $RPATH/libc.so.6  # [linux]
    - $RPATH/libm.so.6  # [linux]
    - $RPATH/libdl.so.2 # [linux]
    - $RPATH/libpthread.so.0 # [linux]
    - $RPATH/librt.so.1 # [linux]
    - $RPATH/libicuuc.so.60  #[linux]
    - $RPATH/libicui18n.so.60 #[linux]
    - $RPATH/libcudart.so.9.2 #[linux]
    - $RPATH/cudart64_92.dll #[win]
    
source:
  git_rev: v2.1
  git_url: https://github.com/cern/tigre.git
  patches:
    - setup_92_v3.patch

requirements:
  build:
    - python
    - numpy {{ numpy }}
    - setuptools
    - cython
    - ripgrep
    - matplotlib
    - scipy

  run:
    - {{ pin_compatible('numpy', min_pin='x.x', max_pin='x.x') }}
    - python
    - matplotlib 
    - scipy
    - libstdcxx-ng # [unix]
    - libgcc-ng # [unix]
    - vc 14 # [win]
    - cudatoolkit=9.2

about:
  home: https://github.com/CERN/TIGRE
  license:  BSD license
  summary: 'TIGRE: Tomographic Iterative GPU-based Reconstruction Toolbox'
